REGIONS = [
    "Toshkent",
    "Toshkent viloyati",
    "Andijon",
    "Farg'ona",
    "Namangan",
    "Samarqand",
    "Buxoro",
    "Navoiy",
    "Qashqadaryo",
    "Surxondaryo",
    "Jizzax",
    "Sirdaryo",
    "Xorazm",
    "Qoraqalpog'iston",
]

DISTRICTS = {
    "Toshkent": [
        "Bektemir",
        "Chilonzor",
        "Mirobod",
        "Mirzo Ulug'bek",
        "Olmazor",
        "Sergeli",
        "Shayxontohur",
        "Uchtepa",
        "Yakkasaroy",
        "Yashnobod",
        "Yunusobod",
        "Yangihayot",
    ],
    "Toshkent viloyati": [
        "Angren",
        "Bekobod",
        "Bo'ka",
        "Bo'stonliq",
        "Chinoz",
        "Chirchiq",
        "Nurafshon",
        "Ohangaron",
        "Olmaliq",
        "Oqqo'rg'on",
        "Parkent",
        "Piskent",
        "Qibray",
        "Quyichirchiq",
        "Toshkent tumani",
        "O'rtachirchiq",
        "Yangiyo'l",
        "Yuqorichirchiq",
        "Zangiota",
    ],
    "Andijon": [
        "Andijon shahri",
        "Andijon tumani",
        "Asaka",
        "Baliqchi",
        "Bo'ston",
        "Buloqboshi",
        "Izboskan",
        "Jalaquduq",
        "Xo'jaobod",
        "Qo'rg'ontepa",
        "Marhamat",
        "Oltinko'l",
        "Paxtaobod",
        "Shahrixon",
        "Ulug'nor",
    ],
    "Farg'ona": [
        "Farg'ona shahri",
        "Qo'qon",
        "Marg'ilon",
        "Quvasoy",
        "Bag'dod",
        "Beshariq",
        "Buvayda",
        "Dang'ara",
        "Farg'ona tumani",
        "Furqat",
        "Oltiariq",
        "Qo'shtepa",
        "Quva",
        "Rishton",
        "So'x",
        "Toshloq",
        "Uchko'prik",
        "Yozyovon",
    ],
    "Namangan": [
        "Namangan shahri",
        "Chortoq",
        "Chust",
        "Kosonsoy",
        "Mingbuloq",
        "Namangan tumani",
        "Norin",
        "Pop",
        "To'raqo'rg'on",
        "Uchqo'rg'on",
        "Uychi",
        "Yangiqo'rg'on",
    ],
    "Samarqand": [
        "Samarqand shahri",
        "Bulung'ur",
        "Ishtixon",
        "Jomboy",
        "Kattaqo'rg'on",
        "Narpay",
        "Nurobod",
        "Oqdaryo",
        "Paxtachi",
        "Payariq",
        "Pastdarg'om",
        "Qo'shrabot",
        "Samarqand tumani",
        "Toyloq",
        "Urgut",
    ],
    "Buxoro": [
        "Buxoro shahri",
        "Kogon shahri",
        "Buxoro tumani",
        "G'ijduvon",
        "Jondor",
        "Kogon tumani",
        "Olot",
        "Peshku",
        "Qorako'l",
        "Qorovulbozor",
        "Romitan",
        "Shofirkon",
        "Vobkent",
    ],
    "Navoiy": [
        "Navoiy shahri",
        "Zarafshon",
        "Karmana",
        "Konimex",
        "Navbahor",
        "Nurota",
        "Qiziltepa",
        "Tomdi",
        "Uchquduq",
        "Xatirchi",
    ],
    "Qashqadaryo": [
        "Qarshi shahri",
        "Shahrisabz shahri",
        "Chiroqchi",
        "Dehqonobod",
        "G'uzor",
        "Kasbi",
        "Kitob",
        "Koson",
        "Mirishkor",
        "Muborak",
        "Nishon",
        "Qamashi",
        "Qarshi tumani",
        "Shahrisabz tumani",
        "Yakkabog'",
    ],
    "Surxondaryo": [
        "Termiz shahri",
        "Angor",
        "Bandixon",
        "Boysun",
        "Denov",
        "Jarqo'rg'on",
        "Muzrabot",
        "Oltinsoy",
        "Qiziriq",
        "Qumqo'rg'on",
        "Sariosiyo",
        "Sherobod",
        "Sho'rchi",
        "Termiz tumani",
        "Uzun",
    ],
    "Jizzax": [
        "Jizzax shahri",
        "Arnasoy",
        "Baxmal",
        "Do'stlik",
        "Forish",
        "G'allaorol",
        "Jizzax tumani",
        "Mirzacho'l",
        "Paxtakor",
        "Yangiobod",
        "Zafarobod",
        "Zomin",
        "Zarbdor",
    ],
    "Sirdaryo": [
        "Guliston shahri",
        "Yangiyer",
        "Shirin",
        "Boyovut",
        "Guliston tumani",
        "Mirzaobod",
        "Oqoltin",
        "Sardoba",
        "Sayxunobod",
        "Sirdaryo tumani",
        "Xovos",
    ],
    "Xorazm": [
        "Urganch shahri",
        "Xiva shahri",
        "Bog'ot",
        "Gurlan",
        "Hazorasp",
        "Xiva tumani",
        "Xonqa",
        "Qo'shko'pir",
        "Shovot",
        "Urganch tumani",
        "Yangiariq",
        "Yangibozor",
        "Tuproqqal'a",
    ],
    "Qoraqalpog'iston": [
        "Nukus shahri",
        "Amudaryo",
        "Beruniy",
        "Chimboy",
        "Ellikqal'a",
        "Kegeyli",
        "Mo'ynoq",
        "Nukus tumani",
        "Qanliko'l",
        "Qo'ng'irot",
        "Qorao'zak",
        "Shumanay",
        "Taxtako'pir",
        "To'rtko'l",
        "Xo'jayli",
    ],
}
